### ISSUE TITLE
The code cannot be executed

### ISSUE THREAD

**Issue by JiaoMaWHU** [duxy-me/ConvNCF#2]
Hey! Thanks for sharing the code.

The code cannot be executed in my environment. And here are my configuration:
Windows 10, Anaconda, Python 3.5+Tensorflow 1.8

I have changed the ' print "" -> print() ' since the code seems to be written in python 2.x. After that, the code still cannot be executed, the errors are as follows:

1.`NULL` appears in the fifth line of saver.py. What does this mean?
2. When I run `python MF_BPR.py`, there is a bug.
```
Traceback (most recent call last):
  File "D:\Anaconda\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\Anaconda\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "E:\BaiduNetdiskDownload\ConvNCF-master\ConvNCF-master\MF_BPR.py", line 355, in _evaluate_input
    item_input = dataset.testNegatives[user] # read negative samples from files
NameError: name 'dataset' is not defined
```
3. Training ConvNCF with `python ConvNCF.py --pretrain=0` also failed, the Traceback is
```
Traceback (most recent call last):
  File "ConvNCF.py", line 580, in <module>
    training(model, dataset, args)
  File "ConvNCF.py", line 319, in training
    eval_feed_dicts = init_eval_model(model, dataset)
  File "ConvNCF.py", line 444, in init_eval_model
    feed_dicts = pool.map(_evaluate_input, range(_dataset.num_users))
  File "D:\Anaconda\envs\tensorflow\lib\multiprocessing\pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\Anaconda\envs\tensorflow\lib\multiprocessing\pool.py", line 608, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'testNegatives'
```
How can I fix it? Looking forward to your suggestion.

**Comment by duxy-me** [comment]
Our code is based on python 2.7 and tensorflow 1.7. Please use the similar configuration and run again.
